### ISSUE TITLE
Missing required element

### ISSUE THREAD

**Issue by milesnimer** [saa-ts-dacs/dacs#39]
With the recent revision of DACS to include 8.2 as a required element, the Multilevel Required element list in Chapter 1 should be updated ([https://github.com/saa-ts-dacs/dacs/blob/master/06_part_I/02_chapter_01.md](https://github.com/saa-ts-dacs/dacs/blob/master/06_part_I/02_chapter_01.md)). The Single-level Required list appears to have already been updated, though.

**Comment by katyrawdon** [comment]
Resolved in #41
