### ISSUE TITLE
Chapter menu missing "Required" status indicator

### ISSUE THREAD

**Issue by milesnimer** [saa-ts-dacs/dacs#40]
The Chapter 13 menu page in the revised version of DACS ([https://github.com/saa-ts-dacs/dacs/blob/master/08_part_II/06_chapter_13/00_authority_record_management.md](https://github.com/saa-ts-dacs/dacs/blob/master/08_part_II/06_chapter_13/00_authority_record_management.md)) is currently missing the "Required" parenthetical status indicator for 13.11.

**Comment by katyrawdon** [comment]
Resolved in #41
