### ISSUE TITLE
Recommend bioghist notes do not include aggrandizing language

### ISSUE THREAD

**Issue by faithc** [saa-ts-dacs/dacs#59]
[Principle 1. Archival description expresses professional ethics and values.](https://saa-ts-dacs.github.io/dacs/04_statement_of_principles.html#1-archival-description-expresses-professional-ethics-and-values)

As a means of harm reduction and prioritizing DEI in archival description, DACS should recommend archivists avoid aggrandizing language in bioghist notes, in particular, writing notes that elevate the accomplishments of white men or white, male-dominated organizations and suppress the voices of women, people of color, and other marginalized communities/groups; that bioghist notes be equitable. See Archives For Black Lives in Philadelphia Anti-Racist Description Resources Metadata Guidelines on Voice and Style (https://github.com/a4blip/A4BLiP/commit/83fd537bf9d1d176eb0991c8c5bcfc38b7010b90)

## I expect that this will require a

- [ ] Minor change to DACS 

## Link(s) to any relevant part(s) of DACS

[2.7 Administrative/Biographical History (Optimum)](https://saa-ts-dacs.github.io/dacs/06_part_I/03_chapter_02/07_administrative_biographical_history.html)
[11.2 Historical Summary](https://saa-ts-dacs.github.io/dacs/08_part_II/04_chapter_11/02_historical_summary.html)

**Comment by faithc** [comment]
Just noticed this duplicates #50 . We can delete the issue I created if that would be appropriate and/or add some content I included here that's not in the other?

Thinking we might end up with a few duplicative/related issues as a result of this process?

**Comment by TinyArchives** [comment]
Is the language in this Issue description intentionally inflammatory? This is a duplicate to Issue #50, as noted above by @faithc, and notes tone and style without pointing fingers or alienating anyone.
