### ISSUE TITLE
3.1.5 Unfamiliar terminology

### ISSUE THREAD

**Issue by kbogan** [saa-ts-dacs/dacs#68]
## Link to relevant DACS principle

[Principle 2. Users are the fundamental reason for archival description.](https://saa-ts-dacs.github.io/dacs/04_statement_of_principles.html#2-users-are-the-fundamental-reason-for-archival-description)

## Describe how DACS does not currently meet this principle
The example in 3.1.5 states, "File contains telex printouts of almost daily discussions between various members of the collaboration team spread out between Ohio, California, and South Africa. Significant gaps for which no telex printouts exist include August 1967-February 1968." How many people know what the term telex means or when it should be used? Is there a better example that can be used here?

## I expect that this will require a

- [X] Minor change to DACS
- [ ] Major change to DACS

## Link(s) to any relevant part(s) of DACS

[3.1 Scope and Content](https://saa-ts-dacs.github.io/dacs/06_part_I/04_chapter_03/01_scope_and_content.html)

**Comment by regineheberlein** [comment]
This relates to #67

**Comment by mfeustle** [comment]
For an example where the obscurity of the format doesn't overshadow the illustration of a note about gaps, this one from the Christopher Small Collection at UNT may work: "The collection consists of one box containing 17 spiral-bound books of photocopies of handwritten notes by Christopher Small; gaps in the numbering of the books indicate that some volumes may be missing."
