### ISSUE TITLE
structuring example records at the ends of chapters in part II

### ISSUE THREAD

**Issue by meau** [saa-ts-dacs/dacs#8]
It looks like example records are stuck on to the last rules of each chapters -- I'm thinking that these should be broken out as their own markdown file. it makes for slightly confusing reading, since the example covers the whole chapter and not just the particular rule -- example: https://github.com/saa-ts-dacs/dacs/blob/master/part_II/chapter_13/9_maintenance_information.md

**Comment by helrond** [comment]
👍 
We'll need to come up with a naming convention, I'd propose simply the chapter number and `_example.md` so the full path for the example above would be `https://github.com/saa-ts-dacs/dacs/blob/master/part_II/chapter_13/9_example.md`
We'll also have to create new pages on the Drupal site, but we can cross that bridge when we get there.

**Comment by katyrawdon** [comment]
This issue has been resolved by pull request #35
