### ISSUE TITLE
Should DACS make a distinction between processing note and revision note?

### ISSUE THREAD

**Issue by regineheberlein** [saa-ts-dacs/dacs#92]
## Link to related tickets
- [Processing note should be a single level required or optimum](https://github.com/saa-ts-dacs/dacs/issues/69)
- [Revision notes should be required · Issue #70 · saa-ts-dacs/dacs · GitHub](https://github.com/saa-ts-dacs/dacs/issues/70)
- [Define minimum required element set for description of each iteration (revision) · Issue #73 · saa-ts-dacs/dacs · GitHub](https://github.com/saa-ts-dacs/dacs/issues/73) 
- [Should we index and display <revisiondesc> ? #1454](https://github.com/projectblacklight/arclight/issues/1454)

## I expect that this will require a

- [ ] Minor change to DACS
- [ ] Major change to DACS

**Comment by regineheberlein** [comment]
This ticket is currently blocking #69, #70, #72, #73

**Comment by regineheberlein** [comment]
Summary of opposing viewpoints expressed across the tickets linked above:

- processing and revising are fundamentally the same activity (with initial processing activities marking the start of continuous revision)
- processing relates to physical objects, revision relates to intellectual description / data / changes to the finding aid only
- processing notes are patron-facing, revision notes are internal-facing

**Comment by regineheberlein** [comment]
What needs to happen to make progress on this ticket:

- compile data points that describe processing activities v. revising activities for each of the three ways of framing the question (see also #72 and #73)
- as practitioners, what problems or pain points do we see with either? what would be a more functional solution?

**Comment by jdean43** [comment]
As a 15 percent solution, we think there could be a clearer justification for this proposal. Clarifying why this is important.
